In [17]:
import numpy as np

In [18]:
array = np.array([1,2,3,4,5])
py_array = [1,2,3,4,5]

print(type(array))
print(type(py_array))


<class 'numpy.ndarray'>
<class 'list'>


In [19]:
print("Numpy Array multiplication", array * 2)
print("Python List multiplication", py_array * 2)


Numpy Array multiplication [ 2  4  6  8 10]
Python List multiplication [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [20]:
import time

In [21]:
# pip install numpy

In [23]:
t = time.time() #start time
[x + x for x in range(10**6)]
print("Lists:", time.time() - t) # finish time - start time

t = time.time() #start time
(np.arange(10**6) * 2)
print("Numpy Array:", time.time() - t) # finish time - start time

Lists: 0.17927765846252441
Numpy Array: 0.007311105728149414


In [24]:
arr = np.arange(0,10,2)

In [25]:
arr

array([0, 2, 4, 6, 8])

In [27]:
zero_arr = np.zeros((2,3))
one_arr = np.ones((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [31]:
mult_arr = np.array([[1,2,3,4],[5,6,7,8]])
print(mult_arr.shape)
print(mult_arr.size)
mult_arr.ndim
mult_arr.dtype

(2, 4)
8


dtype('int32')

In [32]:
mult_arr[0]

array([1, 2, 3, 4])

In [36]:
print(mult_arr[:,:])
print(mult_arr[0 , 1])
print(mult_arr[0 , :])
print(mult_arr[1 , 2])



[[1 2 3 4]
 [5 6 7 8]]
2
[1 2 3 4]
7


In [37]:
np_arr = np.arange(6)
print(np_arr)

[0 1 2 3 4 5]


In [38]:
np_arr1 = np_arr.reshape((2,3))

In [39]:
np_arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 67
print("b[0]", b[0])
print("a[0]", a[0])

b[0] 67
a[0] 1


In [41]:
a = np.array([1,2,3])
b = a.view()
b[0] = 67
print("b[0]", b[0])
print("a[0]", a[0])


b[0] 67
a[0] 67


In [48]:
a1 = np.array([1,2,3])
b1 = np.array([4,5,6])
print(a1+b1)
print(a1-b1)
print(a1*b1)
print(a1/b1)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [49]:
arr = np.array([1,2,3,4,5])
print(arr.sum())
print(arr.mean())
print(arr.std())
print(arr.min())
print(arr.max())
print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))

15
3.0
1.4142135623730951
1
5
[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
